// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"

/**
 * 
 */
namespace FASGameplayTags
{
	// Gameplay effects
	namespace Effect
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SprintEaseOut);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouch);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Falling);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hanging);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sliding);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reloading);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Health_Regen);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Energy_Regen);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Energy_Drain);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Instant);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ADS);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stunned);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);

	}
	
	// Character states
	namespace MovementState
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Falling);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sliding);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hanging);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Death);
	}

	// Gameplay abilities
	namespace Ability
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jump);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ClamberUp);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slide);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fire);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Throw);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reload);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Main);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Secondary);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(AimDownSights);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Melee);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(DryFire);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(EquipGun);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(BulletTime);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(BulletTimeActive);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetSlowMotion);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(UnsetSlowMotion);
		
		// Ability Events
		namespace Event
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(FinishedReloading);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(FinishedADS);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActivatedHitBox);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(DeactivatedHitBox);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(GunEquipped);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(BulletTimeStarted);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(BulletTimeEnded);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Throw);
		}
	}

	// Events
	namespace Event
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hit);
	}

	// Cooldown
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Cooldown_Fire);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Cooldown_Hit);
	
	// Data
	namespace Data
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(JumpCost);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StunDuration);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
	}
	// Cues
	namespace GameplayCue
	{
		namespace Gun
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MuzzleFlare0);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Melee);
		}
		namespace Hit
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(MeleeImpact);
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(BulletImpact);
		}
	}
	
};
